## Numpy Tutorial Brief

#### 1. installing numpy

In [1]:
%pip install numpy
# %conda install numpy

Note: you may need to restart the kernel to use updated packages.


#### 2. importing libraries

In [3]:
import numpy as np

#### 3. Examples and playing with numpy functionalities

In [9]:
# converting to a numpy array
array = list([1,2,3,4,5,6])
arr = np.array(array)

In [10]:
arr

array([1, 2, 3, 4, 5, 6])

In [11]:
# Getting the array shape
arr.shape

(6,)

In [15]:
# Changing array dimensions
arr = arr.reshape(3,2)
print("Array Shape", arr.shape)
arr

Array Shape (3, 2)


array([[1, 2],
       [3, 4],
       [5, 6]])

#### 4. Indexing arrays

In [ ]:
# Arrays are indexed from 0 to n

In [20]:
new_arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

In [21]:
new_arr[4]

5

In [22]:
# Indexing for 2d arrays
new_arr = new_arr.reshape(3,5)
new_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [24]:
# Ex. [[7,8,9], [12,13,14]]
new_arr[1:,1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [25]:
# Ex. [[1,2],[6,7]]
new_arr[:2, :2]

array([[1, 2],
       [6, 7]])

#### 5. Conditinos in numpy arrays

In [27]:
arr_1 = np.array([1,2,3,4,5,6,7,8])
arr_1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
# changing values inside arrays
arr_1 [4:] = 100
arr_1

array([  1,   2,   3,   4, 100, 100, 100, 100])

In [29]:
# conditions applied
arr_1<200

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [32]:
# get the values corresponding to condition true
arr_1[arr_1<50]

array([1, 2, 3, 4])

#### 6. Creating arrays 

In [34]:
# arange function
np.arange(0,10,step=1).reshape(2,5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [51]:
# linspace (start, stop, num:no. of samples)
np.linspace(1,10,20).reshape(5,4)

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263],
       [ 2.89473684,  3.36842105,  3.84210526,  4.31578947],
       [ 4.78947368,  5.26315789,  5.73684211,  6.21052632],
       [ 6.68421053,  7.15789474,  7.63157895,  8.10526316],
       [ 8.57894737,  9.05263158,  9.52631579, 10.        ]])

In [35]:
# arrays multiplication
arr1 = np.arange(0,10,step=1).reshape(2,5)
arr2 = np.arange(0,10).reshape(2,5)
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [36]:
# array of ones
np.ones(shape=(2,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [38]:
# random values from uniform distribution : random.rand(rows,cols)
np.random.rand(3,2)

array([[0.06308224, 0.33822157],
       [0.19063261, 0.99027623],
       [0.81910561, 0.72976728]])

In [39]:
# random values from normal distribution : random.randn(rows,cols)
np.random.randn(3,2)

array([[-0.30781466,  1.12519517],
       [-1.09623319, -0.46444991],
       [-0.95619709,  1.10561114]])

In [48]:
# random integer values from discrete unifrom distribution : 
# random.randint(low, high, size, dtype=int)
np.random.randint(3,50,10).reshape(2,5)

array([[28, 17, 31, 23, 49],
       [46, 25, 38, 39, 44]])

In [49]:
# random samples from continuous uniform dist. 
# (random floats in the half-open interval [0.0, 1.0))
# random.random_sample(size)
np.random.random_sample((2,5))

array([[0.74787327, 0.42821411, 0.97860873, 0.1102691 , 0.56573581],
       [0.70219718, 0.33821344, 0.57876234, 0.25154667, 0.75654047]])

#### 7. Copying and Reference Type variables

In [26]:
# Numpy arrays are reference type variables. If two are equated, 
# it means both are referencing the same memory location


In [40]:
arr_1

array([  1,   2,   3,   4, 100, 100, 100, 100])

In [42]:
arr_2 = arr_1
arr_2

array([  1,   2,   3,   4, 100, 100, 100, 100])

In [43]:
arr_2[4:] = 500
arr_1
# changing arr_2 also affects arr_2. 
# This shows that arr_1 & arr_2 are referencing the same memory space

array([  1,   2,   3,   4, 500, 500, 500, 500])

In [44]:
# Copying into seperate memory space
arr_2 = arr_1.copy()

In [45]:
arr_2[4:] = 1500
arr_1

array([  1,   2,   3,   4, 500, 500, 500, 500])